"""empty message

Revision ID: 117551d76a32
Revises: 
Create Date: 2024-03-25 12:25:20.210879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '117551d76a32'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meal_detail')
    op.drop_table('note')
    with op.batch_alter_table('user_meal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('carbs', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('proteins', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fats', sa.Float(), nullable=True))
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_meal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATETIME(), nullable=True))
        batch_op.drop_column('fats')
        batch_op.drop_column('proteins')
        batch_op.drop_column('carbs')
        batch_op.drop_column('name')

    op.create_table('note',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('data', sa.VARCHAR(length=10000), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meal_detail',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('meal_id', sa.INTEGER(), nullable=True),
    sa.Column('food_name', sa.VARCHAR(length=150), nullable=True),
    sa.Column('amount', sa.FLOAT(), nullable=True),
    sa.Column('carbs', sa.FLOAT(), nullable=True),
    sa.Column('proteins', sa.FLOAT(), nullable=True),
    sa.Column('fats', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['meal_id'], ['user_meal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
